inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Style/Documentation:
  Exclude:
    - lib/core_ext/*.rb
    - spec/support/*.rb

RSpec/FilePath:
  CustomTransform:
    GCloud: gcloud

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/NamedSubject:
  Enabled: false