require:
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Style/Documentation:
  Exclude:
    - lib/core_ext/*.rb
    - spec/support/*.rb

RSpec/SpecFilePathFormat:
  CustomTransform:
    GCloud: gcloud

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Exclude:
    - spec/unit/turbulence/gcloud/action_resources_spec.rb

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ReceiveMessages:
  Enabled: false