version: '3.4'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src
      - gcloud_auth:/root/.config
      - kube_config:/root/.kube
    ports:
    - '25683:25683' # phoneword for CLOUD

volumes:
  gcloud_auth: {}
  kube_config: {}