name: Ruby

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2'] # match with Dockerfile

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run test suite
      run: bundle exec rspec
    - name: Store coverage report
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: spec/coverage
    - name: Run linter check
      run: bundle exec rubocop
